name: Model Training Pipeline

on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Train Model & Upload to Dagshub
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          DAGSHUB_REPO_OWNER: ${{ secrets.DAGSHUB_REPO_OWNER }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
        run: |
          cd backend

          python main.py

          echo "## Model Metrics report" >> report.md
          cat artifacts/model_evaluation/metrics.json >> report.md
